export const navbarData = [
  {
    id: 1,
    routeLink: 'view-user.php',
    icon: 'fa fa-user',
    label: 'User Management',
    module_name: 'User Management',
  },
  {
    id: 2,
    routeLink: 'view-smsgateway.php',
    icon: 'fa fa-comment ',
    label: 'Sms Gateway',
  },
  {
    id: 3,
    // routeLink: 'master-admin/#/3/admissions',

    routeLink: 'add-enquiry.php',
    icon: 'fa fa-university',
    label: 'Admission',
  },
  {
    id: 4,
    routeLink: 'approve-schools.php',
    icon: 'fa fa-graduation-cap',
    label: 'Schools',
  },
  {
    id: 5,
    routeLink: 'bulk-upload-invoices.php',
    icon: 'fa fa-rupee-sign',
    label: 'Fees',
  },
  {
    id: 6,
    routeLink: 'support-queries.php',
    icon: 'fa fa-life-ring',
    label: 'Support',
  },
  {
    id: 7,
    routeLink: 'add-biometric.php',
    icon: 'fa fa-calendar',
    label: 'Biometric',
  },
  {
    id: 8,
    routeLink: 'payment-gateway.php',
    icon: 'fa fa-boxes',
    label: 'Payment Gateway',
  },
  {
    id: 9,
    routeLink: 'school-payments.php',
    icon: 'fa fa-users',
    label: 'Client Payment',
  },
  {
    id: 10,
    routeLink: 'add-api-keys.php',
    icon: 'fa fa-tape',
    label: 'API',
  },
  {
    id: 11,
    routeLink: 'bus_tracking.php',
    icon: 'fa fa-bus-alt',
    label: 'Transport',
  },
  {
    id: 12,
    routeLink: 'add-organization.php',
    icon: 'fa fa-tape',
    label: 'Organization',
  },
  {
    id: 13,
    // routeLink: '#/13/students',
    routeLink: 'bulk-upload-column-students.php',
    icon: 'fa fa-user',
    label: 'Students',
  },
  {
    id: 14,
    routeLink: 'bulk-upload-optional-subjects.php',
    icon: 'fa fa-user',
    label: 'Subjects',
  },
  {
    id: 15,
    routeLink: 'bulk-upload-holiday.php',
    icon: 'fa fa-user ',
    label: 'Bulk Holiday & Event',
  },
  {
    id: 16,
    routeLink: 'delete_request.php',
    icon: 'fa fa-trash',
    label: 'Delete Exam',
  },
  {
    id: 17,
    routeLink: 'view-ay-settings.php',
    icon: 'fa fa-user ',
    label: 'Academic Year Settings',
  },
  {
    id: 18,
    routeLink: 'add_call_category.php',
    icon: 'fa fa-life-ring',
    label: 'Call Category',
  },
  {
    id: 19,
    routeLink: 'upload_author.php',
    icon: 'fa fa-tape',
    label: 'Library',
  },
  {
    id: 20,
    routeLink: 'occupation.php',
    icon: 'fa fa-tape',
    label: 'Occupation',
  },
  {
    id: 21,
    routeLink: 'bulk-upload-petty-expense.php',
    icon: 'fa fa-user ',
    label: 'Expense Bulk',
  },
  {
    id: 22,
    routeLink: 'whatsapp-msg.php',
    icon: 'fa fa-life-ring',
    label: 'WhatsApp',
  },
  {
    id: 23,
    routeLink: 'head-office.php',
    icon: 'fa fa-life-ring',
    label: 'Head Office',
  },
  {
    id: 24,
    routeLink: 'all-school-module.php',
    icon: 'fa fa-life-ring',
    label: 'Bulk Modules Assign',
  },
  {
    id: 25,
    routeLink: 'school_report.php',
    icon: 'fa fa-graduation-cap',
    label: 'Report',
  },
  {
    id: 26,
    routeLink: 'upload_hr_payroll.php',
    icon: 'fa fa-tape',
    label: 'HR Payroll',
  },
  {
    id: 27,
    routeLink: 'school_classes.php',
    icon: 'fa fa-user',
    label: 'Class',
  },
  {
    id: 28,
    routeLink: 'school_terms.php',
    icon: 'fa fa-user',
    label: 'Terms',
  },
  {
    id: 29,
    routeLink: 'bulk-attendance-upload.php',
    icon: 'fa fa-tape',
    label: 'Attendance',
  },
  {
    id: 30,
    routeLink: 'tc-configuration.php',
    icon: 'fa fa-tape',
    label: 'TC',
  },
  {
    id: 31,
    routeLink: 'master-admin/#/31/migration',
    icon: 'fal fa-tachometer',
    label: 'Migration',
  },
  {
    id: 32,
    routeLink: 'master-admin/#/32/boarding-house',
    icon: 'fal fa-tachometer',
    label: 'Barding Pass',
  },
  {
    id: 33,
    routeLink: 'master-admin/#/33/manage-students',
    icon: 'fal fa-tachometer',
    label: 'Manage Students',
  },
];
